const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Function,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Browser,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderClose,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsShare,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Touch.Exps.AbsoluteY,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Function.Cnds.CompareParam,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Browser.Acts.ExecJs
	];
};
self.C3_JsPropNameTable = [
	{StartX: 0},
	{StartY: 0},
	{xx: 0},
	{yy: 0},
	{MaxX: 0},
	{MinX: 0},
	{MaxY: 0},
	{MinY: 0},
	{Connect: 0},
	{Source: 0},
	{N: 0},
	{BackList: 0},
	{UnSlidable: 0},
	{dx: 0},
	{dy: 0},
	{Block: 0},
	{Touch: 0},
	{Function: 0},
	{HaveBlock: 0},
	{Spot: 0},
	{Cam: 0},
	{Mouse: 0},
	{Button: 0},
	{Sprite: 0},
	{TextBox: 0},
	{parent: 0},
	{Line: 0},
	{Text2: 0},
	{w: 0},
	{h: 0},
	{BtnPause: 0},
	{Tween: 0},
	{PauseBox: 0},
	{BtnClose: 0},
	{BtnReset: 0},
	{BtnHome: 0},
	{BlackC: 0},
	{BtnSound: 0},
	{BtnPlay: 0},
	{BtnInfo: 0},
	{Title: 0},
	{InfoBox: 0},
	{BtnBack: 0},
	{n: 0},
	{BtnLevel: 0},
	{Sprite3: 0},
	{txtBtnLevel: 0},
	{LocalStorage: 0},
	{LvCompleteBox: 0},
	{BtnNext: 0},
	{txtLevel: 0},
	{BtnMusic: 0},
	{Array: 0},
	{Audio: 0},
	{GameScore: 0},
	{invite: 0},
	{share: 0},
	{бан: 0},
	{вид: 0},
	{Browser: 0},
	{Текст: 0},
	{FBlock: 0},
	{Pin: 0},
	{FSpot: 0},
	{FLine: 0},
	{FButtons: 0},
	{SelectedBlock: 0},
	{Size: 0},
	{TouchDir: 0},
	{TouchStartX: 0},
	{TouchStartY: 0},
	{CodeText: 0},
	{CodeGet: 0},
	{GlobalN: 0},
	{CheckConnections: 0},
	{BlockPosChange: 0},
	{Pause: 0},
	{LevelComplete: 0},
	{LevelStartTimer: 0},
	{NodeList: 0},
	{Left_: 0},
	{Right_: 0},
	{Top_: 0},
	{Bottom_: 0},
	{Size2: 0},
	{Hor: 0},
	{Ver: 0},
	{Code: 0},
	{Level: 0},
	{Info: 0},
	{Sound: 0},
	{Music: 0},
	{CamOn: 0},
	{Dragging: 0},
	{DragScrollY: 0},
	{DragTouchY: 0},
	{DragTouchSpd: 0},
	{DragTouchDir: 0},
	{MaxTop: 0},
	{MinBottom: 0},
	{PassedLevels: 0},
	{Swipe: 0},
	{LevelSelectTimer: 0},
	{Interstitial_ID: 0},
	{InterstitialVideo_ID: 0},
	{ShowVideoAd: 0},
	{v: 0}
];

self.InstanceType = {
	Block: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Spot: class extends self.ISpriteInstance {},
	Cam: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TextBox: class extends self.ITextInputInstance {},
	Line: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	PauseBox: class extends self.ISpriteInstance {},
	BtnClose: class extends self.ISpriteInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	BlackC: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	InfoBox: class extends self.ISpriteInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	BtnLevel: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	txtBtnLevel: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	LvCompleteBox: class extends self.ISpriteInstance {},
	BtnNext: class extends self.ISpriteInstance {},
	txtLevel: class extends self.ISpriteFontInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	GameScore: class extends self.IInstance {},
	invite: class extends self.ISpriteInstance {},
	share: class extends self.ISpriteInstance {},
	бан: class extends self.IButtonInstance {},
	вид: class extends self.IButtonInstance {},
	Browser: class extends self.IInstance {},
	Текст: class extends self.ITextInstance {},
	FBlock: class extends self.ISpriteInstance {},
	FSpot: class extends self.ISpriteInstance {},
	FLine: class extends self.ISpriteInstance {},
	FButtons: class extends self.ISpriteInstance {}
}