const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Sprite,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Behaviors.scrollto,
		C3.Plugins.Particles,
		C3.Plugins.Button,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{Bullet: 0},
	{Fade: 0},
	{"2_text": 0},
	{Sine: 0},
	{HighScoreFont: 0},
	{LastScoreFont: 0},
	{scoreplus: 0},
	{LiteTween: 0},
	{LiteTween2: 0},
	{completed: 0},
	{schet: 0},
	{odin: 0},
	{Audio: 0},
	{Browser: 0},
	{Function: 0},
	{Touch: 0},
	{DotsUIDS: 0},
	{LinesUIDS: 0},
	{ArmazenamentoLocal: 0},
	{decoratio: 0},
	{Pin: 0},
	{Detector: 0},
	{isConnected: 0},
	{color: 0},
	{Dot: 0},
	{fonsin: 0},
	{BG: 0},
	{LOGO: 0},
	{Sprite13: 0},
	{Rotate: 0},
	{Sprite12: 0},
	{Sprite11: 0},
	{Sprite14: 0},
	{Sprite7: 0},
	{Sprite2: 0},
	{Sprite4: 0},
	{BeamEmpty_LightBrown: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{TiledBackground: 0},
	{effect_demo: 0},
	{effect_level: 0},
	{Fade_menu_sprite: 0},
	{ScrollTo: 0},
	{Frame: 0},
	{Line: 0},
	{Particles: 0},
	{close: 0},
	{go: 0},
	{number: 0},
	{level_number: 0},
	{More_games_Button: 0},
	{Music: 0},
	{ok_button: 0},
	{Pause: 0},
	{Play_button: 0},
	{restart: 0},
	{Pause_icon: 0},
	{level_0002_foreground: 0},
	{imgUnlockScreenMushrooms: 0},
	{imgUnlockTimerBgipad: 0},
	{charAddCoinsPink: 0},
	{charFacebookFeedbackFindingConnection: 0},
	{charBuyScreen: 0},
	{charFacebookFeedbackOffline: 0},
	{clipboard_vectorized: 0},
	{вид: 0},
	{бан: 0},
	{GamePush: 0},
	{Dots: 0},
	{Fade_family: 0},
	{Sound: 0},
	{Combo: 0},
	{Highscore: 0},
	{TimeGame: 0},
	{Score: 0},
	{MegScore: 0},
	{GROUND: 0},
	{ConnectedCount: 0},
	{CurrentColor: 0},
	{CurrentPos: 0},
	{Draging: 0},
	{Level: 0}
];

self.InstanceType = {
	_2_text: class extends self.ITextInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	scoreplus: class extends self.ISpriteFontInstance {},
	completed: class extends self.ISpriteFontInstance {},
	odin: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	DotsUIDS: class extends self.IArrayInstance {},
	LinesUIDS: class extends self.IArrayInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	decoratio: class extends self.ISpriteInstance {},
	Detector: class extends self.ISpriteInstance {},
	Dot: class extends self.ISpriteInstance {},
	fonsin: class extends self.ISpriteInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	LOGO: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	BeamEmpty_LightBrown: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	effect_demo: class extends self.ISpriteInstance {},
	effect_level: class extends self.ISpriteInstance {},
	Fade_menu_sprite: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	close: class extends self.ISpriteInstance {},
	go: class extends self.ISpriteInstance {},
	level_number: class extends self.ISpriteInstance {},
	More_games_Button: class extends self.ISpriteInstance {},
	Music: class extends self.ISpriteInstance {},
	ok_button: class extends self.ISpriteInstance {},
	Pause: class extends self.ISpriteInstance {},
	Play_button: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	Pause_icon: class extends self.ISpriteInstance {},
	level_0002_foreground: class extends self.ISpriteInstance {},
	imgUnlockScreenMushrooms: class extends self.ISpriteInstance {},
	imgUnlockTimerBgipad: class extends self.ISpriteInstance {},
	charAddCoinsPink: class extends self.ISpriteInstance {},
	charFacebookFeedbackFindingConnection: class extends self.ISpriteInstance {},
	charBuyScreen: class extends self.ISpriteInstance {},
	charFacebookFeedbackOffline: class extends self.ISpriteInstance {},
	clipboard_vectorized: class extends self.ISpriteInstance {},
	вид: class extends self.IButtonInstance {},
	бан: class extends self.IButtonInstance {},
	GamePush: class extends self.IInstance {},
	Dots: class extends self.ISpriteInstance {},
	Fade_family: class extends self.ISpriteInstance {}
}