const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Function,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.Spritefont2,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Sin,
		C3.Plugins.Browser,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderClose,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsShare,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.AbsoluteY,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Function.Cnds.CompareParam,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Eponesh_GameScore.Acts.AdsCloseSticky,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Occupied: 0},
	{HasShooter: 0},
	{HasPath: 0},
	{xx: 0},
	{yy: 0},
	{Line: 0},
	{Hole: 0},
	{TargetAngle: 0},
	{Path: 0},
	{MoveAngle: 0},
	{ReadyToGo: 0},
	{Looking: 0},
	{ThePath: 0},
	{Parent: 0},
	{Ball: 0},
	{AllBalls: 0},
	{CurBalls: 0},
	{Clicked: 0},
	{Shooter: 0},
	{Touch: 0},
	{Function: 0},
	{Tween: 0},
	{RingEffect: 0},
	{Particles: 0},
	{Cam: 0},
	{Button: 0},
	{TextBox: 0},
	{txtShooter: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{TiledBackground: 0},
	{BtnPlay: 0},
	{BtnInfo: 0},
	{BtnSound: 0},
	{Title: 0},
	{BtnMusic: 0},
	{BlackC: 0},
	{InfoBox: 0},
	{BtnClose: 0},
	{n: 0},
	{BtnLevel: 0},
	{txtBtnLevel: 0},
	{Sprite3: 0},
	{BtnBack: 0},
	{Array: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{txtLevel: 0},
	{PauseBox: 0},
	{Sine: 0},
	{Sine2: 0},
	{BtnReset: 0},
	{BtnHome: 0},
	{LvCompleteBox: 0},
	{BtnNext: 0},
	{BtnPause: 0},
	{Browser: 0},
	{GameScore: 0},
	{share: 0},
	{invite: 0},
	{вид: 0},
	{бан: 0},
	{BtnPlay2: 0},
	{старт: 0},
	{Текст: 0},
	{Текст2: 0},
	{Pin: 0},
	{FHole: 0},
	{FPath: 0},
	{MoveTo: 0},
	{FBall: 0},
	{FShooter: 0},
	{FButtons: 0},
	{FLine: 0},
	{FPopups: 0},
	{BallsSpeed: 0},
	{Pause: 0},
	{LevelComplete: 0},
	{Size: 0},
	{LevelStartTimer: 0},
	{CodeText: 0},
	{CodeGet: 0},
	{Lose: 0},
	{v: 0},
	{Left_: 0},
	{Right_: 0},
	{Top_: 0},
	{Bottom_: 0},
	{Left_2: 0},
	{Right_2: 0},
	{Top_2: 0},
	{Bottom_2: 0},
	{vLevel: 0},
	{vSound: 0},
	{vMusic: 0},
	{vPassedLevels: 0},
	{Size2: 0},
	{Hor: 0},
	{Ver: 0},
	{Code: 0},
	{Level: 0},
	{Info: 0},
	{Sound: 0},
	{Music: 0},
	{CamOn: 0},
	{Dragging: 0},
	{DragScrollY: 0},
	{DragTouchY: 0},
	{DragTouchSpd: 0},
	{DragTouchDir: 0},
	{MaxTop: 0},
	{MinBottom: 0},
	{PassedLevels: 0},
	{Swipe: 0},
	{LevelSelectTimer: 0},
	{AllLevels: 0},
	{AllLevelsN: 0},
	{Interstitial_ID: 0},
	{InterstitialVideo_ID: 0},
	{ShowVideoAd: 0},
	{menu: 0},
	{run: 0},
	{ban: 0},
	{full: 0},
	{vLastX: 0},
	{vLastY: 0}
];

self.InstanceType = {
	Hole: class extends self.ISpriteInstance {},
	Path: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Shooter: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	RingEffect: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Cam: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	TextBox: class extends self.ITextInputInstance {},
	txtShooter: class extends self.ISpriteFontInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BlackC: class extends self.ISpriteInstance {},
	InfoBox: class extends self.ISpriteInstance {},
	BtnClose: class extends self.ISpriteInstance {},
	BtnLevel: class extends self.ISpriteInstance {},
	txtBtnLevel: class extends self.ISpriteFontInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	txtLevel: class extends self.ISpriteFontInstance {},
	Line: class extends self.ISpriteInstance {},
	PauseBox: class extends self.ISpriteInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	LvCompleteBox: class extends self.ISpriteInstance {},
	BtnNext: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	GameScore: class extends self.IInstance {},
	share: class extends self.ISpriteInstance {},
	invite: class extends self.ISpriteInstance {},
	вид: class extends self.IButtonInstance {},
	бан: class extends self.IButtonInstance {},
	BtnPlay2: class extends self.ISpriteInstance {},
	старт: class extends self.IButtonInstance {},
	Текст: class extends self.ITextInstance {},
	Текст2: class extends self.ITextInstance {},
	FHole: class extends self.ISpriteInstance {},
	FPath: class extends self.ISpriteInstance {},
	FBall: class extends self.ISpriteInstance {},
	FShooter: class extends self.ISpriteInstance {},
	FButtons: class extends self.ISpriteInstance {},
	FLine: class extends self.ISpriteInstance {},
	FPopups: class extends self.ISpriteInstance {}
}